#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/generate_update_deploy_config.sh <dist_dir> [options]

Options:
  --repo <owner/repo>         Repository slug (optional)
  --tag <vX.Y.Z...>           Release tag (optional)
  --deploy-path <remote-path> Remote base path for update host (optional)
  -h, --help                  Show this help
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

dist_dir="$1"
shift

if [[ ! -d "$dist_dir" ]]; then
  echo "Error: dist directory not found: $dist_dir" >&2
  exit 1
fi

repo=""
tag=""
deploy_path=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      repo="${2:-}"
      shift 2
      ;;
    --tag)
      tag="${2:-}"
      shift 2
      ;;
    --deploy-path)
      deploy_path="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      exit 1
      ;;
  esac
done

if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq is required" >&2
  exit 1
fi

build_info_path="${dist_dir%/}/BUILD_INFO.txt"
feed_path="${dist_dir%/}/update-feed-v1.json"
sha_path="${dist_dir%/}/SHA256SUMS.txt"

for required in "$build_info_path" "$feed_path" "$sha_path"; do
  if [[ ! -f "$required" ]]; then
    echo "Error: required artifact missing: $required" >&2
    exit 1
  fi
done

version_name="$(awk -F= '$1=="versionName"{print $2}' "$build_info_path" | tr -d '\r' | tail -n1)"
version_code="$(awk -F= '$1=="versionCode"{print $2}' "$build_info_path" | tr -d '\r' | tail -n1)"
commit_sha="$(awk -F= '$1=="commit"{print $2}' "$build_info_path" | tr -d '\r' | tail -n1)"
if [[ -z "$version_name" || -z "$version_code" ]]; then
  echo "Error: BUILD_INFO.txt missing version metadata" >&2
  exit 1
fi

release_subdir="releases/${version_name}"
remote_release_path=""
remote_feed_path=""
remote_sha_path=""
if [[ -n "$deploy_path" ]]; then
  remote_release_path="${deploy_path%/}/${release_subdir}"
  remote_feed_path="${deploy_path%/}/update-feed-v1.json"
  remote_sha_path="${deploy_path%/}/SHA256SUMS.txt"
fi

generated_at_epoch_ms="$(($(date +%s) * 1000))"
entries_count="$(jq -r '.payload.entries | length' "$feed_path")"
max_version_code="$(jq -r '[.payload.entries[].versionCode] | max' "$feed_path")"
channels_json="$(jq -c '[.payload.entries[].channel] | unique | sort' "$feed_path")"

shopt -s nullglob
apk_files=( "${dist_dir%/}"/*.apk )
shopt -u nullglob
apk_names_json="$(printf '%s\n' "${apk_files[@]##*/}" | jq -Rsc 'split("\n") | map(select(length > 0))')"

deploy_dir="${dist_dir%/}/deploy"
mkdir -p "$deploy_dir"

cat >"${deploy_dir}/update-server.env" <<EOF
# Generated by scripts/generate_update_deploy_config.sh
PUSHGO_UPDATE_SCHEMA_VERSION=1
PUSHGO_UPDATE_VERSION_NAME=${version_name}
PUSHGO_UPDATE_VERSION_CODE=${version_code}
PUSHGO_UPDATE_TAG=${tag}
PUSHGO_UPDATE_REPO=${repo}
PUSHGO_UPDATE_RELEASE_SUBDIR=${release_subdir}
PUSHGO_UPDATE_REMOTE_RELEASE_PATH=${remote_release_path}
PUSHGO_UPDATE_REMOTE_FEED_PATH=${remote_feed_path}
PUSHGO_UPDATE_REMOTE_SHA256_PATH=${remote_sha_path}
PUSHGO_UPDATE_FEED_FILE=update-feed-v1.json
PUSHGO_UPDATE_SHA256_FILE=SHA256SUMS.txt
PUSHGO_UPDATE_CACHE_FEED=public,max-age=120,must-revalidate
PUSHGO_UPDATE_CACHE_SHA256=public,max-age=300,must-revalidate
PUSHGO_UPDATE_CACHE_RELEASE_APK=public,max-age=31536000,immutable
EOF

jq -n \
  --arg repo "$repo" \
  --arg tag "$tag" \
  --arg commit "$commit_sha" \
  --arg versionName "$version_name" \
  --argjson versionCode "$version_code" \
  --arg releaseSubdir "$release_subdir" \
  --arg remoteReleasePath "$remote_release_path" \
  --arg remoteFeedPath "$remote_feed_path" \
  --arg remoteShaPath "$remote_sha_path" \
  --argjson generatedAtEpochMs "$generated_at_epoch_ms" \
  --argjson entriesCount "$entries_count" \
  --argjson maxVersionCode "$max_version_code" \
  --argjson channels "$channels_json" \
  --argjson apks "$apk_names_json" \
  '{
    schemaVersion: 1,
    generatedAtEpochMs: $generatedAtEpochMs,
    source: {
      repo: ($repo | if . == "" then null else . end),
      tag: ($tag | if . == "" then null else . end),
      commit: ($commit | if . == "" then null else . end)
    },
    release: {
      versionName: $versionName,
      versionCode: $versionCode,
      releaseSubdir: $releaseSubdir,
      remoteReleasePath: ($remoteReleasePath | if . == "" then null else . end),
      remoteFeedPath: ($remoteFeedPath | if . == "" then null else . end),
      remoteSha256Path: ($remoteShaPath | if . == "" then null else . end),
      apkFiles: $apks
    },
    feed: {
      file: "update-feed-v1.json",
      sha256File: "SHA256SUMS.txt",
      entriesCount: $entriesCount,
      maxVersionCode: $maxVersionCode,
      channels: $channels
    },
    cachePolicy: {
      feed: "public,max-age=120,must-revalidate",
      sha256: "public,max-age=300,must-revalidate",
      releaseApk: "public,max-age=31536000,immutable"
    }
  }' >"${deploy_dir}/update-server-manifest.json"

update_root="${deploy_path:-/var/www/update.pushgo.cn/android}"
cat >"${deploy_dir}/nginx-update-server.conf" <<EOF
# Generated by scripts/generate_update_deploy_config.sh
# Drop this snippet under your server {} block.

location = /android/update-feed-v1.json {
    alias ${update_root%/}/update-feed-v1.json;
    add_header Cache-Control "public,max-age=120,must-revalidate";
    try_files \$uri =404;
}

location = /android/SHA256SUMS.txt {
    alias ${update_root%/}/SHA256SUMS.txt;
    add_header Cache-Control "public,max-age=300,must-revalidate";
    try_files \$uri =404;
}

location /android/releases/ {
    alias ${update_root%/}/releases/;
    add_header Cache-Control "public,max-age=31536000,immutable";
    try_files \$uri =404;
}
EOF

cat >"${deploy_dir}/deploy-rsync-example.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 3 ]]; then
  cat <<'USAGE'
Usage:
  deploy-rsync-example.sh <dist_dir> <user@host> <remote_base_path>
USAGE
  exit 1
fi

dist_dir="$1"
remote_user_host="$2"
remote_base_path="$3"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
"${repo_root}/scripts/publish_update_artifacts.sh" "$dist_dir" "$remote_user_host" "$remote_base_path"
EOF
chmod +x "${deploy_dir}/deploy-rsync-example.sh"

cat >"${deploy_dir}/README.md" <<'EOF'
# Update Server Deploy Bundle

Generated files:

- `update-server-manifest.json`: machine-readable deployment metadata.
- `update-server.env`: env-style key/value config for ops scripts.
- `nginx-update-server.conf`: cache/header/path snippet for update host.
- `deploy-rsync-example.sh`: example wrapper for artifact publishing.
EOF

echo "Generated deploy bundle under ${deploy_dir}"
